name: BlueMapPlayerControl
version: '${project.version}'
main: com.technicjelle.bluemapplayercontrol.BlueMapPlayerControl
folia-supported: true
api-version: 1.13
depend:
  - BlueMap
author: TechnicJelle
description: Adds player hiding functionality to BlueMap
website: https://github.com/TechnicJelle/BlueMapPlayerControl

commands:
  visible:
    usage: /<command> [hide | show] [player]
    description: Изменяет видимость на BlueMap
    permission: visible

permissions:
  visible:
    default: true
  visible.*:
    default: op
    children:
      visible.self:
        default: true
        children:
          visible.self.toggle: true
          visible.self.show: true
          visible.self.hide: true
      visible.others:
        default: op
        children:
          visible.others.toggle: true
          visible.others.show: true
          visible.others.hide: true
  visible.self.toggle:
    default: true
  visible.self.show:
    default: true
  visible.self.hide:
    default: true
  visible.others.toggle:
    default: op
  visible.others.show:
    default: op
  visible.others.hide:
    default: op
